# -*- coding: utf-8 -*-
"""mnist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xNJKOL3xsPrnMk3py0MGpurV6D5Cz492
"""

import tensorflow as tf

mnist = tf.keras.datasets.mnist # 28x28 images of hand-written digits 0-9

(x_train, y_train), (x_test, y_test) = mnist.load_data()

x_train = tf.keras.utils.normalize(x_train,axis=1)
x_test = tf.keras.utils.normalize(x_train,axis=1)


import matplotlib.pyplot as plt
plt.imshow(x_train[0], cmap = plt.cm.binary) #(,not a color img/blackwhite) 
plt.show()

x_train